# Generated by Django 3.1.2 on 2020-10-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login_form',
            fields=[
                ('Username', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
    ]
