# Generated by Django 3.1.2 on 2020-10-19 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('homeground', models.CharField(max_length=20)),
                ('Budget', models.IntegerField()),
                ('owner_fname', models.CharField(max_length=20)),
                ('owner_mname', models.CharField(max_length=20, null=True)),
                ('owner_lname', models.CharField(max_length=20)),
                ('total_players', models.IntegerField()),
                ('no_of_for', models.IntegerField()),
                ('no_of_ind', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Logins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.login_form')),
                ('team_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.team')),
            ],
        ),
    ]
