# Generated by Django 3.1.2 on 2020-10-19 15:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_auto_20201019_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('p_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('speciality', models.CharField(max_length=15)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('nationality', models.CharField(max_length=20)),
                ('base_price', models.IntegerField(validators=[django.core.validators.MinValueValidator(10000000), django.core.validators.MaxValueValidator(20000000)])),
            ],
        ),
        migrations.CreateModel(
            name='Player_stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches', models.IntegerField()),
                ('bat_avg', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('strike_rate', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('runs', models.IntegerField()),
                ('thirties', models.IntegerField()),
                ('fifties', models.IntegerField()),
                ('best_score', models.IntegerField()),
                ('wickets', models.IntegerField()),
                ('bowl_avg', models.DecimalField(decimal_places=2, max_digits=4)),
                ('economy', models.DecimalField(decimal_places=2, max_digits=4)),
                ('best_bowl_perf', models.TextField()),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.player')),
            ],
        ),
    ]
