# Generated by Django 3.1.2 on 2020-10-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_player_player_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_stats',
            name='best_bowl_perf',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='player_stats',
            name='bowl_avg',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='player_stats',
            name='economy',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
