# Generated by Django 3.1.2 on 2020-10-24 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0007_auto_20201024_1858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bids',
            old_name='current_bid',
            new_name='bid',
        ),
    ]
